### ISSUE TITLE
In pip site, only version 6.23.1 is available

### ISSUE THREAD

**Issue by dradoudine** [Ericsson/codechecker#4282] opened 2024-07-01 07:10 UTC
**Describe the bug**
When I install with pip I don't see 6.24 version
In site https://pypi.org/project/codechecker/ latest version is not 6.24

**CodeChecker version**

**To Reproduce**
Steps to reproduce the behaviour:

1. Run command '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behaviour**
What you expected to happen.

**Desktop (please complete the following information)**
 - OS: [e.g. Linux]
 - Browser: [e.g. Firefox, Chrome]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem.

**Comment by whisperity** [comment] 2024-07-01 08:54
Sort-of duplicate of #4261.

**Closed** 2024-07-01 08:54 UTC
Labels: duplicate :busts_in_silhouette:, CI :package:, package-Python 🐍
