### ISSUE TITLE
[pip] CodeChecker parse error: codechecker_report_converter/report/output/html/static/layout.html No such file or directory

### ISSUE THREAD

**Issue by pansila** [Ericsson/codechecker#3515] opened 2021-11-22 09:59 UTC
**Describe the bug**
FileNotFoundError: [Errno 2] No such file or directory

**CodeChecker version**
```
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version 
---------------------------------------------------------------
Base package version | 6.18.0 
Package build date   | 2021-11-12T13:13                        
Git commit ID (hash) | 153b0e09efc715fd16eee815eecf454f9f79f7f1
Git tag information  | 6.18 
---------------------------------------------------------------
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Run command 'CodeChecker parse ./reports -e html -o ./reports_html'
2. See error:
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/codechecker_common/cli.py", line 206, in main
    sys.exit(args.func(args))
  File "/usr/local/lib/python3.8/dist-packages/codechecker_analyzer/cmd/parse.py", line 410, in main
    html_builder = report_to_html.HtmlBuilder(
  File "/usr/local/lib/python3.8/dist-packages/codechecker_report_converter/report/output/html/html.py", line 134, in __init__
    self._layout = Template(get_file_content(
  File "/usr/local/lib/python3.8/dist-packages/codechecker_report_converter/report/output/html/html.py", line 90, in get_file_content
    with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/codechecker_report_converter/report/output/html/static/layout.html'
```

**Expected behaviour**
see index.html

**Desktop (please complete the following information)**
 - OS: ubuntu 18.04
 - Browser: Firefox
 - Version: ??

**Additional context**
Though it was fixed by #3395

**Comment by whisperity** [comment] 2021-11-30 08:33
Duplicate of #3499, fixed by #3502.

**Closed by whisperity** 2021-11-30 08:33 UTC
Labels: bug :bug:, duplicate :busts_in_silhouette:, CI :package:, tools :hammer_and_wrench:, report-converter
