### ISSUE TITLE
`TypeError: %d format: a number is required, not NoneType`

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#3954] opened 2023-07-12 11:29 UTC
Sorry I don't have a smaller test case but with:
` CodeChecker store $(pwd)/codechecker-results/ -n firefox_$(date "+%Y%m%d%H%M") --url firefox`

fails with some files with:
```
TypeError: %d format: a number is required, not NoneType
Call stack:
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python3/codechecker_common/cli.py", line 233, in <module>
    main()
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python3/codechecker_common/cli.py", line 209, in main
    sys.exit(args.func(args))
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python3/codechecker_server/cmd/server.py", line 425, in __handle
    main(args)
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python3/codechecker_server/cmd/server.py", line 1009, in main
    server_init_start(args)
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python3/codechecker_server/cmd/server.py", line 972, in server_init_start
    environ)
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python3/codechecker_server/server.py", line 1121, in start_server
    p.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
```

Version:
```

[INFO 2023-07-12 11:28] - CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version
---------------------------------------------------------------
Base package version | 6.23.0
Package build date   | 2023-07-10T22:29
Git commit ID (hash) | 78f686380be330dfb5af2abe8052ac127f2be10b
Git tag information  | 6.23
---------------------------------------------------------------

[INFO 2023-07-12 11:28] - CodeChecker web version:
------------------------------------------------------------------------------
Kind                                | Version
------------------------------------------------------------------------------
Base package version                | 6.23.0
Package build date                  | 2023-07-10T22:29
Git commit ID (hash)                | 78f686380be330dfb5af2abe8052ac127f2be10b
Git tag information                 | 6.23
Server supported Thrift API version | 6.53
Client Thrift API version           | 6.53
------------------------------------------------------------------------------
```

I have a bunch of results:
```
---------------------------------------------------------
Number of processed analyzer result files        | 8275
Number of analyzer reports                       | 581322
Number of source files                           | 1358
Number of source files with source code comments | 0
Number of blame information files                | 0
---------------------------------------------------------
```

**Comment by bruntib** [comment] 2023-07-25 14:43
Hi,
Unfortunately I can't reproduce this bug. Are there some further error logs? I mean this stack trace contains no information about which `%d` gets a `None` value. Could you, please, check the logs both on client and server side?
Thank you!

**Comment by bruntib** [comment] 2023-08-30 07:35
Hi,
I close this ticket for now. But in case the problem persists, please, feel free to reopen it.
Thank you!

**Closed by bruntib** 2023-08-30 07:35 UTC
