### ISSUE TITLE
Internal server error: The API version you are using is not supported by this server (server API version: v6.53)!

### ISSUE THREAD

**Issue by RobertoFioravanti** [Ericsson/codechecker#4055] opened 2023-10-24 08:50 UTC
I'm running [whisperity](https://github.com/whisperity)/[CodeChecker-Action](https://github.com/whisperity/CodeChecker-Action)

```
[INFO 2023-10-24 08:16] - CodeChecker web version:
------------------------------------------------------------------------------
Kind                                | Version                                 
------------------------------------------------------------------------------
Base package version                | 6.23.0                                  
Package build date                  | 2023-10-24T08:16                        
Git commit ID (hash)                | fa41e4e5d9566b5a4f5a80a27bddec73a5146f5a
Git tag information                 | 6.23                                    
Server supported Thrift API version | 6.54                                    
Client Thrift API version           | 6.54                                    
------------------------------------------------------------------------------
```

When attempting to updload results 
error 'The API version you are using is not supported by this server (server API version: v6.53)!' raised.

```
Storing results to server
  [INFO 2023-10-24 08:16] - Storing analysis results for run 'xxxxxxxxxxxx: xxxxx'
  [INFO 2023-10-24 08:16] - Checking local passwords or tokens in /home/runner/.codechecker.passwords.json
  [INFO 2023-10-24 08:16] - Checking for local valid sessions.
  [ERROR 2023-10-24 08:16] - Internal server error: The API version you are using is not supported by this server (server API version: v6.53)!
```

The same action with the same settings but with Server supported Thrift API version | 6.53  was working.      
```
------------------------------------------------------------------------------
Kind                                | Version                                 
------------------------------------------------------------------------------
Base package version                | 6.23.0                                  
Package build date                  | 2023-10-03T16:48                        
Git commit ID (hash)                | 6d7351efb56f58b4e3b24b6057f738f456c5405d
Git tag information                 | 6.23                                    
Server supported Thrift API version | 6.53                                    
Client Thrift API version           | 6.53                                    
------------------------------------------------------------------------------

 [INFO 2023-10-03 16:48] - Storing analysis results for run 'xxxxxxxxxxxxxxxx: xxxxxx'
  [INFO 2023-10-03 16:48] - Checking local passwords or tokens in /home/runner/.codechecker.passwords.json
  [INFO 2023-10-03 16:48] - Checking for local valid sessions.
  [INFO 2023-10-03 16:48] - Logging in using pre-configured credentials...
  [INFO 2023-10-03 16:48] - Authentication successful.
  [INFO 2023-10-03 16:48] - Processing report files done.
  [INFO 2023-10-03 16:48] - Get missing file content hashes from the server...
  [INFO 2023-10-03 16:48] - Get missing file content hashes done.
  [INFO 2023-10-03 16:48] - Get file content hashes which do not have blame information from the server...
  [INFO 2023-10-03 16:48] - Get file content hashes which do not have blame information done.
  [INFO 2023-10-03 16:48] - Collecting review comments ...
  [INFO 2023-10-03 16:48] - Collecting review comments done.
  [INFO 2023-10-03 16:48] - Building report zip file...
  [INFO 2023-10-03 16:48] - Collecting blame information for source files...
  [INFO 2023-10-03 16:48] - Collecting blame information done.
  [INFO 2023-10-03 16:48] - Building report zip file (/tmp/tmpi35hgpfu.zip) done.
```

**Comment by whisperity** [comment] 2023-10-24 08:59
The versions of the server and the client do not match up, as it is evident from the Git commit ID in the version output. You're using a client that is newer than the server. In this case, it is likely that the client expects APIs that do not yet exist on the server. As a precaution, the connection is terminated in advance.

6.23.0 is still ongoing work, and has not been released yet!

Please ensure you use the same versions for the server and the client, preferably a tested release version. By default, the Action should get the latest **release** version from PyPI.

**Comment by bruntib** [comment] 2023-11-27 12:33
I close this ticket, because this is the expected behavior of CodeChecker as @whisperity mentioned. If you have further questions, feel free to comment. Thank you!

**Closed by bruntib** 2023-11-27 12:33 UTC
Labels: question :grey_question:, Won't fix :-1:, version :tada:
