### ISSUE TITLE
Taint Configuration doesn't work

### ISSUE THREAD

**Issue by Logyiyi** [Ericsson/codechecker#3643] opened 2022-04-01 14:32 UTC
I encounter some problems with the taint analysis configuration. I completely followed the instructions in the official manual but got no results. I don't know if I'm using it the wrong way or if the format of the configuration file has changed. My version is 15.0.0. The Code and Configuration file are as follows. Please help me.

Code:
void test1(char t){
std::cout<<t;
}
void mysink(char t){
std::cout<<t;
}
int main(int argc, char** argv) {
char x = 'x';
test1(x);
mysink(x);
return 0;
}

Configuration File:
Propagations:

Name: test1
DstArgs: [0]
Sinks:
Name: mysink
Args: [0]

**Comment by steakhal** [comment] 2022-04-28 14:51
> I completely followed the instructions in the official manual but got no results.
Confirmed. The `clangsa:` prefix on the config was missing in the example. I'll address that.

Here is an example which works for me:

```bash
cat > myconfig.yaml << EOF
Propagations:
 - Name: test1
   DstArgs: [-1]

Sinks:
 - Name: mysink
   Args: [0]
EOF

cat > db.json << EOF
[{
  "directory": ".",
  "command": "/usr/bin/g++ test.cpp",
  "file": "test.cpp"
}]
EOF

cat > test.cpp << EOF
#include <iostream>

char test1() {
  char ch;
  std::cin >> ch;
  return ch;
}

void mysink(char t) {
  std::cout << t;
}

int main() {
  char x = test1();
  mysink(x);

  int n;
  scanf("%d", &n);
  mysink(n);
}
EOF

PATH="/path/to/llvm-project/build/bin:$PATH" \
CC_ANALYZERS_FROM_PATH=yes \
CodeChecker analyze db.json -e alpha.security.taint --checker-config 'clangsa:alpha.security.taint.TaintPropagation:Config=myconfig.yaml' -o reports
CodeChecker parse reports
```

This reports:
```
 [HIGH] test.cpp:15:3: Untrusted data is passed to a user-defined sink [alpha.security.taint.TaintPropagation]
   mysink(x);
   ^
 
 [HIGH] test.cpp:19:3: Untrusted data is passed to a user-defined sink [alpha.security.taint.TaintPropagation]
   mysink(n);
   ^

Found 2 defect(s) in test.cpp
```

---

Notice the change:
```
--checker-config 'clangsa:alpha.security.taint.TaintPropagation:Config=myconfig.yaml'
                  ^^^^^^^^-- this was missing in the example invocation
```

**Comment by steakhal** [comment] 2022-05-02 08:40
I think we can close this one. @bruntib

**Comment by bruntib** [comment] 2022-05-02 09:20
@Logyiyi can we close this ticket? Is @steakhal's answer working for you?

**Closed** 2022-05-16 14:40 UTC
Labels: bug :bug:, clang sa :dragon:
