### ISSUE TITLE
Crash when relative path is given for SQLite db

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#1046] opened 2017-10-17 13:19 UTC
```
(venv) xazax@cc:~/Checker_Xerces$ CodeChecker server --sqlite db.sqlite --not-host-only -v 15010
Traceback (most recent call last):
  File "/mnt/storage/xazax/Checker_Xerces/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 101, in main
    args.func(args)
  File "/mnt/storage/xazax/Checker_Xerces/codechecker/build/CodeChecker/lib/python2.7/libcodechecker/libhandlers/server.py", line 332, in __handle
    main(args)
  File "/mnt/storage/xazax/Checker_Xerces/codechecker/build/CodeChecker/lib/python2.7/libcodechecker/libhandlers/server.py", line 414, in main
    os.makedirs(os.path.dirname(args.sqlite))
  File "/mnt/storage/xazax/Checker_Xerces/codechecker/venv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''
```
Also, default product is not created. Is this bug or intended?

**Comment by gyorb** [comment] 2017-10-17 15:28
Did you try to give just a workspace directory (config and Default db will be created)? By default everything will be in sqlite.

@whisperity do we create a Default product if there is an explicit configuration database given? I think we will not create a Default product it in this case by design. You can add the products by hand after the server was started.

We should not crash if a relative path was given.

**Closed** 2020-03-23 16:08 UTC
Labels: CLI :computer:, bug :bug:
