### ISSUE TITLE
"cmd del" returns "Done" but isn't doing anything

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#1271] opened 2017-12-23 10:32 UTC
```
$ CodeChecker cmd del -n firefox_201711181753  --url firefox
[11:31] - Done.
```
But the build remains available
(same with the web interface)

**Comment by whisperity** [comment] 2017-12-24 09:41
I tried reproducing this issue but couldn't. First thought was that `_` in the run name was causing problems, but using the exact same run name it properly disappears from my server. I'm running f7702d043acd501fae47c54bbdcea473edfece77. (Latest `master` at the point of writing this comment.)

What does the server and the client say with `--verbose debug`?

**Comment by sylvestre** [comment] 2018-03-06 09:28
I just tried again with 6.6:
```
$  CodeChecker cmd del -n firefox_201711230945  --url firefox --verbose debug
[DEBUG][2018-03-06 10:20:27] {system} [20304] <140626768656128> - util.py:366 split_product_url() - Parsing product url 'firefox'
[DEBUG][2018-03-06 10:20:27] {system} [20304] <140626768656128> - util.py:407 split_product_url() - Result: With 'http' on server 'localhost:8001', product 'firefox'
[DEBUG][2018-03-06 10:20:27] {system} [20304] <140626768656128> - credential_manager.py:29 __init__() - Loading clientside session config.
[DEBUG][2018-03-06 10:20:27] {system} [20304] <140626768656128> - credential_manager.py:35 __init__() - /var/lib/jenkins/.codechecker.passwords.json
[DEBUG][2018-03-06 10:20:27] {system} [20304] <140626768656128> - credential_manager.py:52 __init__() - /var/lib/jenkins/.codechecker.session.json
[DEBUG][2018-03-06 10:20:27] {system} [20304] <140626768656128> - credential_manager.py:29 __init__() - Loading clientside session config.
[DEBUG][2018-03-06 10:20:27] {system} [20304] <140626768656128> - credential_manager.py:35 __init__() - /var/lib/jenkins/.codechecker.passwords.json
[DEBUG][2018-03-06 10:20:27] {system} [20304] <140626768656128> - credential_manager.py:52 __init__() - /var/lib/jenkins/.codechecker.session.json
[DEBUG][2018-03-06 10:20:28] {system} [20304] <140626768656128> - client.py:274 setup_client() - returning service client
[INFO][2018-03-06 10:22:20] {system} [20304] <140626768656128> - cmd_line_client.py:811 handle_remove_run_results() - Done.

```

**Comment by whisperity** [comment] 2018-03-06 10:45
Currently, the `Done.` message is printed every time the handler for the delete action returns. It signifies the operation's end. However, I am curious about what the **server** says. The API handler returns `False` if the deletion of a run fails &ndash; which is agreeably promptly disregarded by the client... &ndash;. The error itself is printed to the server's log.

**Comment by csordasmarton** [comment] 2020-03-13 12:34
Removing a run was refactored in #2343 pull request.
https://github.com/Ericsson/codechecker/blob/12fedce8f506ebc992df177d8755bc54689c9a08/web/client/codechecker_client/cmd_line_client.py#L1391-L1395
Now it will remove the given runs with one API request and it will write and error message on failure.

I couldn't reproduce this problem with the latest CodeChecker so I will close this issue now but if you still experience the same problem we can reopen this issue.

**Closed by csordasmarton** 2020-03-13 12:34 UTC
Labels: server :desktop_computer:
