### ISSUE TITLE
AttributeError: 'str' object has no attribute 'write'

### ISSUE THREAD

**Issue by flok99** [Ericsson/codechecker#3114] opened 2020-12-21 14:31 UTC
Hi,

During upload to the 'CodeChecker server' instance, I got the following error (several times):

[WARNING 2020-12-21 15:26] - Check name wasn't found in the plist file '..._template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist'
. 
[WARNING 2020-12-21 15:26] - Check name wasn't found in the plist file '..._template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist'
. 
[WARNING 2020-12-21 15:26] - Check name wasn't found in the plist file '..._template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist'
. 
[WARNING 2020-12-21 15:26] - Check name wasn't found in the plist file '..._template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist'
. 
[WARNING 2020-12-21 15:26] - Error during processing reports from the plist file: ..._template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist
Traceback (most recent call last):
  File "/home/fhe/codechecker/build/CodeChecker/lib/python3/codechecker_common/plist_parser.py", line 216, in parse_plist_file
    plistlib.dump(plist, path)
  File "/usr/lib64/python3.6/plistlib.py", line 1034, in dump
    writer = _FORMATS[fmt]["writer"](fp, sort_keys=sort_keys, skipkeys=skipkeys)
  File "/usr/lib64/python3.6/plistlib.py", line 460, in __init__
    file.write(PLISTHEADER)
AttributeError: 'str' object has no attribute 'write'
[WARNING 2020-12-21 15:26] - <class 'AttributeError'>
[WARNING 2020-12-21 15:26] - 'str' object has no attribute 'write'

Note: also the CodeChecker-server itself logged this error:

[WARNING 2020-12-21 15:26] - Check name wasn't found in the plist file '/tmp/tmpph08v29q/reports/..._clangsa_456aff074dbf28fd35287ef098df8265.plist'.
[WARNING 2020-12-21 15:26] - Check name wasn't found in the plist file '/tmp/tmpph08v29q/reports/..._clangsa_456aff074dbf28fd35287ef098df8265.plist'.
[WARNING 2020-12-21 15:26] - Error during processing reports from the plist file: /tmp/tmpph08v29q/reports/..._clangsa_456aff074dbf28fd35287ef098df8265.plist
Traceback (most recent call last):
  File "/home/fhe/codechecker/build/CodeChecker/lib/python3/codechecker_common/plist_parser.py", line 216, in parse_plist_file
    plistlib.dump(plist, path)
  File "/usr/lib64/python3.6/plistlib.py", line 1034, in dump
    writer = _FORMATS[fmt]["writer"](fp, sort_keys=sort_keys, skipkeys=skipkeys)
  File "/usr/lib64/python3.6/plistlib.py", line 460, in __init__
    file.write(PLISTHEADER)
AttributeError: 'str' object has no attribute 'write'
[WARNING 2020-12-21 15:26] - <class 'AttributeError'>
[WARNING 2020-12-21 15:26] - 'str' object has no attribute 'write'
[INFO 2020-12-21 15:26] - 'Anonymous' stored results (8441 KB) to run 'my-project' in 9.59 seconds.
[INFO 2020-12-21 15:26] - 127.0.0.1:36516 -- [Anonymous] POST /Default/v6.37/CodeCheckerService

**Comment by flok99** [comment] 2020-12-21 14:47
The web-interface says:

NUMBER OF FAILED FILES 
0

NUMBER OF CHECKERS REPORTING FAULTS 
5

**Comment by csordasmarton** [comment] 2020-12-21 15:09
Could you please attach the plist file (template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist) which failed to analyze?

**Comment by flok99** [comment] 2020-12-21 18:13
Hi,

Took a bit, but here it is:

[template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist.txt](https://github.com/Ericsson/codechecker/files/5725814/template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist.txt)

**Comment by csordasmarton** [comment] 2020-12-21 18:24
@flok99 I think your clang version is too old: `clang version 3.4.2`. I don't think CodeChecker supports so old clang version.

**Comment by flok99** [comment] 2020-12-21 18:31
Oh darn, indeed. And it is even mentioned on the codechecker website. Sorry for the inconvenience.
Maybe this also explains that other bug I opened today.

**Comment by csordasmarton** [comment] 2020-12-21 18:33
Sorry, the problem is different. There is a bug inside CodeChecker, so I created a fix for this: #3115. Could you please try it out whether it works for you?

**Comment by flok99** [comment] 2020-12-21 19:00
Tried it.

I now get (4x):

[WARNING 2020-12-21 19:49] - Check name wasn't found in the plist file '/template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist'.

It was then around 160kB.

and during the store:

[ERROR 2020-12-21 19:51] - Invalid plist file 'template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist': Document is empty, line 1, column 1 (template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist, line 1)

After that I checked the filesize again and suddenly it was 0 bytes.

I think I made no mistake with the merge:

```
-            plistlib.dump(plist, path)
+            with open(path, 'rb+') as plist_file:
+                plistlib.dump(plist, plist_file)
```

I did not forget to fix this in the venv by the way.

**Comment by csordasmarton** [comment] 2020-12-21 19:27
The problem was that I opened the file in append mode instead of writing mode. I updated my patch, now it should work.

**Comment by flok99** [comment] 2020-12-22 07:26
Good morning,

After applying the patch and a re-run, I get the following. After that, the files it complains about are 0 bytes in size - NOT before.

```
$ CodeChecker store ./results4 -n my-project 2>&1 | tee blog4
[INFO 2020-12-22 08:19] - Storing analysis results for run 'my-project'
[INFO 2020-12-22 08:19] - Checking local passwords or tokens in .codechecker.passwords.json
[INFO 2020-12-22 08:19] - Password file not found.
[INFO 2020-12-22 08:19] - Checking for local valid sessions.
[WARNING 2020-12-22 08:19] - Check name wasn't found in the plist file 'map.c_clangsa_456aff074dbf28fd35287ef098df8265.plist'. 
[WARNING 2020-12-22 08:19] - Error during processing reports from the plist file: map.c_clangsa_456aff074dbf28fd35287ef098df8265.plist
[WARNING 2020-12-22 08:19] - <class 'TypeError'>
[WARNING 2020-12-22 08:19] - list indices must be integers or slices, not str
[ERROR 2020-12-22 08:19] - Invalid plist file 'map.c_clangsa_456aff074dbf28fd35287ef098df8265.plist': Document is empty, line 1, column 1 (map.c_clangsa_456aff074dbf28fd35287ef098df8265.plist, line 1)
[ERROR 2020-12-22 08:19] - Failed to parse plist map.c_clangsa_456aff074dbf28fd35287ef098df8265.plist
[WARNING 2020-12-22 08:19] - Check name wasn't found in the plist file 'template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist'. 
[WARNING 2020-12-22 08:19] - Error during processing reports from the plist file: template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist
[WARNING 2020-12-22 08:19] - <class 'TypeError'>
[WARNING 2020-12-22 08:19] - list indices must be integers or slices, not str
[ERROR 2020-12-22 08:19] - Invalid plist file 'template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist': Document is empty, line 1, column 1 (template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist, line 1)
[ERROR 2020-12-22 08:19] - Failed to parse plist template.c_clangsa_6662832d7e50ead8bd22348d2e979cc4.plist
Traceback (most recent call last):
  File "/home/fhe/codechecker/build/CodeChecker/lib/python3/codechecker_common/plist_parser.py", line 186, in parse_plist_file
    file_path = mentioned_files[diag['location']['file']]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/fhe/codechecker/build/CodeChecker/lib/python3/codechecker_common/plist_parser.py", line 186, in parse_plist_file
    file_path = mentioned_files[diag['location']['file']]
TypeError: list indices must be integers or slices, not str
[INFO 2020-12-22 08:19] - Processing report files done.
[INFO 2020-12-22 08:19] - Collecting review comments ...
[INFO 2020-12-22 08:19] - Collecting review comments done.
[INFO 2020-12-22 08:19] - Storing results to the server...
[INFO 2020-12-22 08:20] - Storage finished successfully.
```

**Comment by csordasmarton** [comment] 2020-12-22 10:03
@flok99 It looks like my patch solved the first problem but this is another bug. I updated my PR and I think the second commit will solve this problem too.

**Comment by flok99** [comment] 2020-12-22 10:48
Tried it and no more errors! The files also don't get truncated any longer. So I think we can conclude it now works.

**Closed** 2021-01-11 15:38 UTC
Labels: analyzer :chart_with_upwards_trend:, bug :bug:
