### ISSUE TITLE
codechecker_false_positive does not change the Review status column to False positive

### ISSUE THREAD

**Issue by sanchi4** [Ericsson/codechecker#3077] opened 2020-12-07 18:07 UTC
codechecker_false_positive does not change the Review status column to False positive

**To Reproduce**
Steps to reproduce the behaviour:

https://codechecker.readthedocs.io/en/v6.9.0/user_guide/#source-code-comments-for-review-status

**Expected behaviour**
Review status column should change to False positive

**Comment by csordasmarton** [comment] 2020-12-08 09:44
@gyorb created a patch which may solve your problem: #3078. Could you please try it out?

By the way how is you `CodeChecker store` command looks like? Do you use the `--trim-path-prefix` option?

How the source code comment looks like in your source code? Maybe there is a typo. Could you share with us the comment and the line below it?

**Comment by csordasmarton** [comment] 2021-02-23 12:18
I think the #3078 patch solved this problem, because I can not reproduce this problem anymore. Please try it again with the master branch.

I will close this ticket for now, but if you still experience this problem we can reopen it.

**Closed by csordasmarton** 2021-02-23 12:18 UTC
Labels: bug :bug:
