### ISSUE TITLE
file content hash check before store

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1321] opened 2018-01-24 14:30 UTC
Collect the source file content hashes during analysis and recheck them before store.
Store should fail if the source code is modified since the analysis.

Storing the reports with a modified source code since the analysis will now show the results properly.

**Comment by whisperity** [comment] 2018-01-24 18:34
Is this a duplicate of #1320?

**Comment by dkrupp** [comment] 2018-01-24 18:58
yes, i guess this once can be closed.

**Closed by dkrupp** 2018-01-24 18:58 UTC
Labels: Kind: Enhancement, Target: Command-line
