### ISSUE TITLE
Unrecognized compiler options

### ISSUE THREAD

**Issue by baloghadamsoftware** [Ericsson/codechecker#3952] opened 2023-07-10 16:00 UTC
**Describe the bug**
Some compiler options (mostly irrelevant to static analysis) are not recognized by Clang, therefore the analysis fails.

**CodeChecker version**
6.22.1

**To Reproduce**
1. Check out the Linux kernel
2. Create a .config file by executing e.g. 'make menuconfig', then press 'Save' and 'Exit'
3. Build the kernel while logging it, e.g.: 'CodeChecker log -o linux.json -b 'make -j4'
4. Split linux.json to at least 4 equal parts, called 'linux*.json'
5. Analyze the code: 'CodeChecker analyze1 -o analyzis linux1.json'

**Expected behaviour**
The analyzers should analyze the code. Instead, the analysis of most files fail because Clang does not recognize some gcc options and CodeCheckers does not remove them:
-mindirect-branch-cs-prefix
-fno-allow-store-data-races
-fsanitize=bound-strict
-ftrivial-auto-var-init=zero
-fno-hoisting
-fsched-pressure
-falign-loops=1

**Desktop (please complete the following information)**
 - OS: Ubuntu Linux
 - Browser: n/a
 - Version: Distribution version 23.04, kernel version 6.2.0

**Additional context**

**Comment by dkrupp** [comment] 2023-07-19 15:29
some more: 
-fno-lifetime-dse

**Comment by jaskij** [comment] 2023-08-31 03:13
Also `-fmerge-constants`

**Comment by jaskij** [comment] 2023-08-31 03:15
I think that, because of how fast toolchains move, and because this list will only grow, we should get the option to have a file we can point CodeChecker at which will list compilation flags to remove.

Hmm.... maybe some `jq` black magic preprocessing of `compile_commands.json` will work?

**Comment by jaskij** [comment] 2023-08-31 03:36
Okay, a quick-and-dirty Python script to remove unwanted flags. Modify to your needs.

```python
#!/user/bin/env python

import json

TO_REMOVE = (
        '-fmerge-constants',
        '-mindirect-branch-cs-prefix',
        '-fno-allow-store-data-races',
        '-fsanitize=bound-strict',
        '-ftrivial-auto-var-init=zero',
        '-fno-hoisting',
        '-fsched-pressure',
        '-falign-loops=1',
        )

f = open('compile_commands.json', 'r+')
commands = json.load(f)
for sub in TO_REMOVE:
    print(f"Replacing '{sub}'")
    for c in commands:
        c['command'] = c['command'].replace(sub,'')
f.seek(0)
f.truncate()
json.dump(commands, f, indent=4, ensure_ascii=False)
```

**Comment by bruntib** [comment] 2023-10-05 10:05
Fixed by #4028

**Closed by bruntib** 2023-10-05 10:05 UTC
Labels: enhancement :star2:, analyzer :chart_with_upwards_trend:, clang sa :dragon:, clang-tidy :dragon:, config :gear:

**Comment by whisperity** [comment] 2023-10-05 14:06
@jaskij The problem is when flags are not to be removed as-is, but transformed. Like a flag that takes two arguments in GCC but only one in Clang. Or a flag with 0 or 1 becoming a no-foo and foo flag, which is still supported in Clang but in that way.

I would much prefer implementing a Clang flag which turns the presence of unknown flags into warnings instead of errors and just using that flag when passing from CodeChecker.

**Comment by jaskij** [comment] 2023-10-05 21:23
@whisperity unless those flags impact the correctness of your code, I don't see any harm in simply removing them.

That said, nothing is stopping anyone from extending the handling to massage those flags into versions which Clang will accept.

**Comment by whisperity** [comment] 2023-10-06 07:18
True, @jaskij. My point was that if and when we design a mechanism by which the user can control the filtering of the compilation commands, this must be kept in mind. I do agree with the general idea, having to change the code and rebuild the package isn't the most ergonomic thing here.

**Comment by jaskij** [comment] 2023-10-10 03:49
@whisperity I do agree that, ultimately, this should be handled by the user within codechecker itself. The existing solution of "manually" removing those files from the compilation database and then pestering maintainers to update the hardcoded filter is suboptimal.
