### ISSUE TITLE
Add a watcher to kill stuck jobs

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#1168] opened 2017-11-22 17:43 UTC
I have a  job which has been running for more 24 hours (probably a bug in the checker).
Would be great if "CodeChecker check" could kill jobs which have been running forever!

**Comment by sylvestre** [comment] 2017-11-23 08:46
After 48 hours, I killed the service, the python bt was:
```
[ERROR] [09:45] - Running check failed. 
Traceback (most recent call last):
  File "/data/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python2.7/libcodechecker/libhandlers/check.py", line 454, in main
    analyze_module.main(analyze_args)
  File "/data/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python2.7/libcodechecker/libhandlers/analyze.py", line 421, in main
    analyzer.perform_analysis(args, context, actions, metadata)
  File "/data/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python2.7/libcodechecker/analyze/analyzer.py", line 135, in perform_analysis
    'capture_analysis_output' in args)
  File "/data/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python2.7/libcodechecker/analyze/analysis_manager.py", line 483, in start_workers
    pool.join()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 469, in join
    assert self._state in (CLOSE, TERMINATE)
AssertionError
Exception KeyError: KeyError(140371586914048,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Exception AttributeError: "'NoneType' object has no attribute 'getpid'" in <Finalize object, dead> ignored
Exception AttributeError: "'NoneType' object has no attribute 'getpid'" in <Finalize object, dead> ignored
```

**Comment by whisperity** [comment] 2017-11-26 19:00
This backtrace is essentially standard, and thus useless to see which check made the underlying analyser hang, as this message happens from the fact that you killed the whole process pool while a subprocess was still running.

Can you please show a list on what checks were turned on for the analysis?

So far, a workaround could be to set the timeout in Jenkins, so that the entire analysis job is sniped if the timeout is reached. I'll try to look into a graceful way of handling long-running tasks, but we need to make sure to see a good approximation on how long an analysis is. Simply saying `10 minutes` won't be enough, as the speed of analysis depends a lot on the particular hardware, and the amount of checks enabled.

The sad truth about Clang SA at this point is that checks can (and in some cases, even undocumentedly so **do**) depend on presumptions and state generated by each other. Which means that a badly written check pair both turned on at the same time could be too much for the analyser to swallow.

Assuming you have enough disk space underlying the Jenkins workspace, you could set the analyses to run as `--verbose debug_analyzer`. This verbosity mode is less verbose than `debug` (it does not print a lot of additional yadda), but it prints the actual `clang` and `clang-tidy` invocations verbatim. This could help to pinpoint exactly which file was the one last analysed when the hang happened.

**Comment by dkrupp** [comment] 2017-11-28 14:39
But maybe we could create a watchdog per analyzer invocation. I think we could set up a reasonable timeout (say 10 mins) for analyzing a single build action. Unfortunately we saw "alpha checkers" that were run indefinitely long. we could even put the whole build action into the failed dir in this case.

**Comment by whisperity** [comment] 2017-12-01 15:03
Once my patch is merged, @sylvestre, please be so kind that if a hanging happens you send us details on which check resulted in the hanging. Every extra field case benefits the community in ironing out the kinks of Clang.

**Comment by sylvestre** [comment] 2017-12-01 15:04
Sure, will do with pleasure :)

**Comment by sylvestre** [comment] 2017-12-05 09:11
Doesn't seem to work.
http://relman-ci.mozilla.org/job/firefox-codechecker/494/console
It has been running for the last 8 hours :/

Running with
`CodeChecker check -j 13 -b "hg pull -u && hg update -r default && ./mach build -j 23" -o codechecker-results --enable-all $CHECKERS --timeout 600
`

**Comment by whisperity** [comment] 2017-12-05 09:31
The timeout is applied *per analyzer invocation* (so each clang and clang-tidy process started), not for the *whole* job.

**Comment by sylvestre** [comment] 2017-12-05 09:31
Sure but it should have killed the jobs by now?

**Comment by whisperity** [comment] 2017-12-05 10:08
If each and every analyzer runs for at most 10 minutes, no. According to your log, clang tidy is running right now and it seemingly works good. You have around 6000 analyzer invocations to handle. Assuming the thing runs single thread, with 600 as per analyzer timeout, it's a total of ~6000*600 seconds timeout total. Which is around a thousand hours, so around 42 **days**.

**Comment by whisperity** [comment] 2017-12-05 10:13
The problem is not the analysis jobs being killed. That should work. The analyzer concluded... There seems to be another error here, which is independent to analysis hang.

**Comment by whisperity** [comment] 2017-12-05 10:25
I ran a quick grep on your output, one of the analyzer invocations actually timed out. Also, enabling the `debug` checkers as you did produces a lot of extra output and can result in analysis failure in certain cases, there were some of your analysis invocations that printed long traces and errors.

But the hanging itself doesn't happen from this issue, your individual analyses finish timely.

**Closed** 2018-01-23 15:55 UTC
Labels: Kind: Enhancement, Target: Analyzer handling
