### ISSUE TITLE
improved filtering

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#348] opened 2016-08-09 13:11 UTC
Improve filtering to be able to save filter configurations for later reuse. This could improve the grouping of results too.
-  [ ] a filter should be identified by a name which could be reused later
-  [ ] command line client should be able to use the stored filter for getting the results

**Comment by whisperity** [comment] 2017-07-12 08:13
Duplicate of better explained #689.

**Closed by whisperity** 2017-07-12 08:13 UTC
Labels: cmdline, database, enhancement, webgui
