### ISSUE TITLE
saargs parameter not processed correctly if the parameter contains space

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#433] opened 2016-11-04 08:44 UTC
The problem appears, if the file given in the --saargs argument has a parameter which has whitespace in its value as shown in the example below.

Reproduction:
~/work/codechecker/CodeChecker/bin/CodeChecker quickcheck --saargs ./gcc.saargs3 --analyzers clangsa -b "gcc -c hello.c"

hello.c: 
empty file

gcc.saargs3:
-D__UINT_LEAST8_TYPE__='unsigned char'

Error:
[14021] <140620018566976> - analysis_manager.py:143 check() - Analyzing hello.c with clangsa failed.
[14021] <140620018566976> - analysis_manager.py:147 check() - clang-3.9: error: no input files

**Comment by Xazax-hun** [comment] 2016-11-14 11:06
This might be fixed now. Please check with the newest master.

**Comment by bruntib** [comment] 2017-02-13 14:15
I can't reproduce the error neither.

**Closed** 2017-05-16 09:30 UTC
Labels: bug, cmdline
