### ISSUE TITLE
Incremental analysis with log-analyze-store pipeline marks reports in unmodified files as resolved

### ISSUE THREAD

**Issue by irishrover** [Ericsson/codechecker#1987] opened 2019-03-16 12:56 UTC
**Describe the bug**

Incremental analysis with log-analyze-store pipeline marks reports in unmodified files as resolved.

**To Reproduce**
Steps to reproduce the behavior
1) `git clone https://github.com/remonbonbon/makefile-example.git`
2) Apply this patch:

```
diff --git a/src/main.cpp b/src/main.cpp
index 7a8ab6e..e040bdf 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -1,5 +1,5 @@
 #include "main.h"
 
 int main() {
-       hello("world");
+       hello("world\0");
 }
diff --git a/src/mod/mod.cpp b/src/mod/mod.cpp
index b86824e..eb22dd2 100644
--- a/src/mod/mod.cpp
+++ b/src/mod/mod.cpp
@@ -2,5 +2,5 @@
 #include <iostream>
 
 void hello(const std::string &msg) {
-       std::cout << "Hello, " << msg << "!" << std::endl;
+       std::cout << "Hello, " << std::move(msg) << "!" << std::endl;
 }
```

3) ```make clean```
4) Run server: ```CodeChecker server --not-host-only -v 8080 &```
5) Log make file: ```CodeChecker log -o make.json -b "make"```
6) Run analysis ```CodeChecker analyze make.json -o REPORTS --enable-all```
7) Store the results: ```CodeChecker store REPORTS/ --name make_test --url http://localhost:8080/Default```
8) Open CodeChecker in your browser and make sure there are ```3``` unresolved reports for the project.
9) Remove REPORTS dir: ```rm -rf REPORTS```
10) Remove ```std::move``` in ```mod.cpp``` and re-log: ```CodeChecker log -o make.json -b "make"``` (```make.json``` now contains only 1 file - ```mod.cpp```)
11) Repeat ```(6)``` & ```(7)```
8) Open CodeChecker in your browser. No unresolved reports! 

**CodeChecker version**
```
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.9.1                                   
Package build date   | 2019-03-12T20:49                        
Git commit ID (hash) | 54ce393b67dda9dd2463d59208252aa0265358d4
Git tag information  | 6.9.1                                   
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.9.1                                   
Package build date            | 2019-03-12T20:49                        
Git commit ID (hash)          | 54ce393b67dda9dd2463d59208252aa0265358d4
Git tag information           | 6.9.1                                   
Configuration schema          | v6.0                                    
Database schema               | v6.0                                    
Server supported API (Thrift) | 6.15                                    
Client API (Thrift)           | 6.15                                    
------------------------------------------------------------------------

```
**Expected behavior**

After fixing ```1``` issue, there must be ```2``` issues remaining, not ```0```.

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser Chrome

**Comment by irishrover** [comment] 2019-03-19 12:19
Any ideas?

**Comment by gyorb** [comment] 2019-03-20 09:43
Which clang version did you use? Did you run clang-tidy too?

**Comment by irishrover** [comment] 2019-03-20 17:55
> Which clang version did you use? Did you run clang-tidy too?

Hm, I have clang-6.0 installed in my system. But there's a clang-7.1 in my $PATH.
And for some reasons CodeCheckers was using 6.0 instead of 7.1.
After I provided a full path to clang-7.1 the issue is no more reproduced.

**Comment by irishrover** [comment] 2019-03-20 19:41
Can you reproduce it?

**Comment by irishrover** [comment] 2019-03-20 20:05
Seems I found the reason. There was only 1 issue in my file. And I fixed it. So CodeChecker warns:

``
[WARNING 2019-03-20 23:02] - There is no report to store. After uploading these results the previous reports become resolved.
``
But why other, non-modified, files are marked as resolved?

**Comment by gyorb** [comment] 2019-03-26 07:50
During storage the detection status is updated for each report. If the report is not found in a later analysis we mark it as resolved because we assume it has been fixed. In this case if you store 0 reports  so all of them will be marked as resolved.

You can read more about the detection status changes [here](https://github.com/Ericsson/codechecker/blob/0e7fee1b9a9c46185507e78bc9a4d95c2180c5f5/web/server/www/userguide/userguide.md#userguide-detection-status)

**Comment by irishrover** [comment] 2019-03-26 07:57
> During storage the detection status is updated for each report. If the report is not found in a later analysis we mark it as resolved because we assume it has been fixed. In this case if you store 0 reports so all of them will be marked as resolved.
> 
> You can read more about the detection status changes [here](https://github.com/Ericsson/codechecker/blob/0e7fee1b9a9c46185507e78bc9a4d95c2180c5f5/web/server/www/userguide/userguide.md#userguide-detection-status)

Thanks for your reply. But my question was about unchanged files only - why did they mark resolved?

**Comment by irishrover** [comment] 2019-03-26 08:22
I suspect that there's something wrong in 

https://github.com/Ericsson/codechecker/blob/master/web/server/codechecker_server/api/report_server.py#L2271

?

**Comment by gyorb** [comment] 2019-03-26 08:27
So you mean you store the same report which is found and stored again but its status is changed to resolved?

**Comment by irishrover** [comment] 2019-03-26 08:41
> So you mean you store the same report which is found and stored again but its status is changed to resolved?
> Did the report path change?

My scenario is the following (see the first post for details):

1) there 3 files: a.cpp, b.cpp, c.cpp, each having 1 issue.
2) generate compilation db, it has 3 items.
3) analyze and store: there 3 issue reports in CodeChecker now.
4) fix the only issue in a.cpp, re-generate compilation db (1 item only as the only 1 file has changed)
5) analyze this compilation db into a new reports directory, store result into the existing CodeChecker DB (product).
6) CodeChecker shows all the issues were resolved! But in fact only the a.cpp was fixed.

**Comment by gyorb** [comment] 2019-03-29 13:13
What happens here is that you are using a separate report directory for the second analysis. If you want to change the report status right, you have to use the same report directory for all of the analysis runs.

If you use the same report directory, the plist reports will be overwritten only for that a.cpp (with an empty plist) and when you store the results only the report from a.cpp will be updated. (in the example you described)

With the separate report directory there will be 0 reports and when you store this CodeChecker assumes you have fixed all the reports so each report will be updated as resolved.

**Comment by irishrover** [comment] 2019-03-29 13:27
> What happens here is that you are using a separate report directory for the second analysis. If you want to change the report status right, you have to use the same report directory for all of the analysis runs.
> 
> If you use the same report directory, the plist reports will be overwritten only for that a.cpp (with an empty plist) and when you store the results only the report from a.cpp will be updated. (in the example you described)
> 
> With the separate report directory there will be 0 reports and when you store this CodeChecker assumes you have fixed all the reports so each report will be updated as resolved.

Thanks. Now it's clear.

**Comment by gyorb** [comment] 2019-03-29 14:13
can we close this issue or you still have some questions?

**Comment by irishrover** [comment] 2019-03-29 14:16
Yes, close please. Thanks again.

пт, 29 мар. 2019 г. в 17:13, Gyorgy Orban <notifications@github.com>:

**Comment by gyorb** [comment] 2019-03-29 14:17
your welcome

**Comment by gyorb** [comment] 2019-04-02 10:43
Hi, 

No problem we can continue the discussion.

Yes, as the help mentions if you use the `--force` during store it will remove all the already stored reports from the run.
The results of using the `--force` flag is:
- the detection status will be set to new for all the stored reports
- detection date will be the new store date (you will not know when the bug was actually introduced if you need this information)

**Comment by irishrover** [comment] 2019-04-02 10:53
I thought that 

> 
>                        By default,
>                         CodeChecker would keep reports that were coming from
>                         files not affected by the analysis, and only
>                         incrementally update defect reports for source files
>                         that were analysed.

means "if you don't pass reports for some of files, their status will not be changed on the server".

**Comment by gyorb** [comment] 2019-04-02 15:11
The description in the help message refers to what I previously described that if you use the same report directory the report only for the changed files are updated.

If you use our diff feature (local report directory compared to a stored run in the db) to provide a correct diff the whole report list is needed locally too, that is why we do the local incremental report change.
If you clean the reports directory this can not be done (If we do not see a report hash we assume it was fixed).
If you analyze your whole project, store it and after that you just analyze the part of it in a separate directory and you store the second report directory on the same run a lot of results will be marked as resolved. But in real life they are not resolved you just did not analyze that part.

As an improvement if we would not want to send the plist files, we would still need at least the full report hash list to update the detection status correctly on the server side (this would require some api changes).

**Comment by irishrover** [comment] 2019-04-04 17:26
Thanks!

**Comment by irishrover** [comment] 2019-04-04 17:36
I tried to re-analyze files:

> CodeChecker analyze ... -o REPORTS full_command_list.json
> git pull --rebase && ninja chrome
> CodeChecker analyze ... -o REPORTS changed_command_list.json
> CodeChecker store ...

And get: 

>The following source file contents changed since the latest analysis:
>Please analyze your project again to update the reports!
> <list of files that definitely have just been re-analyzed!>

It seems that https://github.com/Ericsson/codechecker/blob/master/web/client/codechecker_client/cmd/store.py#L275 is incorrect: why we compare all the files with the given plist? Why not compare only the corresponding files? May be we should reset `file_to_mtime` in https://github.com/Ericsson/codechecker/blob/master/web/client/codechecker_client/cmd/store.py#L256

What do you think? Thanks.

**Comment by gyorb** [comment] 2019-04-09 06:48
Is it possible that when you do the second `changed_command_list.json` it will not contain all the changed files? I mean maybe some header was changed which was included by a.cpp and b.cpp (and the bug path went through the header).
If a.cpp was changed (will be in the `changed_command_list.json`)  in that case the report file for a.cpp will be updated but if b.cpp did not changed  (will not be in the `changed_command_list.json`) the report for that file will not be updated and during the store we will detect that there is a mismatch in the last update time of the report of b.cpp and the header and will not store it.
Could you verify that this is the case?

We made the storage quite strict because the bug paths can be messed up (on the UI) if we store the wrong file content for a plist report. If we would store the report for b.cpp the content of the header file would be overwritten but the bug path not (because it was not reanalyzed). 

In case of changing the way how we store the reports the detection status update logic needs to be changed because it depends on the report list.

**Comment by gyorb** [comment] 2019-04-12 07:06
Were some *.c or *.cpp files renamed during that git pull?

**Comment by irishrover** [comment] 2019-04-12 08:51
> Were some *.c or *.cpp files renamed during that git pull?

Sorry, I had no time to check it yet.

**Comment by irishrover** [comment] 2019-04-23 19:00
Sorry for a long delay.
I was able to reproduce the problem in a small demo.
[re-analyze-demo.tar.gz](https://github.com/Ericsson/codechecker/files/3109138/re-analyze-demo.tar.gz)

Unpack and run `run.sh`. You'll find 

```
[WARNING 2019-04-23 21:39] - The following source file contents changed since the latest analysis:
 - /home/zzz/Documents/makefile/src/mod/mod2.cpp
Please analyze your project again to update the reports!

```

although `mod2.cpp` has just been re-analyzed while also changed `main.cpp` wasn't.

**Comment by irishrover** [comment] 2019-04-26 05:29
@gyorb, hi. Did you have a chance to see my sample?

**Comment by gyorb** [comment] 2019-04-26 15:57
Sorry, not yet. Probably at the beginning of the next week.

**Comment by gyorb** [comment] 2019-04-30 14:29
For some reason it does not produce an error on all of our machines, 
but we found an environment where we could reproduce it.
PR #2102 should fix this problem.

**Comment by irishrover** [comment] 2019-04-30 14:30
Thanks a llt!

**Closed** 2019-05-29 15:19 UTC
Labels: question :grey_question:
