### ISSUE TITLE
ipv6 support for the web-server

### ISSUE THREAD

**Issue by irishrover** [Ericsson/codechecker#2708] opened 2020-05-03 18:04 UTC
Our internal Docker-based web-service allows to run other web-services only as listening to ipv6.
Can you please help me how to achieve this?

I use web/Docker with the minor diff:

`CMD ["CodeChecker", "server", "--workspace", "/workspace", "--not-host-only", "--port", "8080", "--verbose", "debug"]
`
I have no ideas for ipv6 except for 

```
-            client_host, client_port = self.client_address
+            client_host, client_port = self.client_address[:2]
```

and
 
```
     daemon_threads = False
+    address_family = socket.AF_INET6
```

It helps but Thrift wrapper in JS fails to get the product list:

Uncaught Thrift.TApplicationExceptioncode: 6message: "Bad data encounted in numeric data"
codeCheckerDBAccess.js:7166 

It's

```
codeCheckerDBAccess_v6.codeCheckerDBAccessClient.prototype.recv_getRunData = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x; // <--------------- line 7166
  }

```

Callstack looks like

```
codeCheckerDBAccess_v6.codeCheckerDBAccessClient.recv_getRunData (codeCheckerDBAccess.js:7166)
codeCheckerDBAccess_v6.codeCheckerDBAccessClient.getRunData (codeCheckerDBAccess.js:7135)
_populateRuns (ListOfRuns.js:299)
postCreate (ListOfRuns.js:188)
create (_WidgetBase.js:84)
postscript (_WidgetBase.js:50)
(anonymous) (dojo.js:15)
postCreate (ListOfRuns.js:466)
create (_WidgetBase.js:84)
postscript (_WidgetBase.js:50)
```

I have no ideas what to check next. Can you please advice me?

**Comment by whisperity** [comment] 2020-05-04 07:06
It seems the server might work fine, but the client code has some issue.

Could you try inspecting the network communication in your browser? Or if it fails, fall back to curl to manually try to fetch data from the Thrift API, using a running server, to rule out if it's a server or a clientside issue. Other methods such as echoing an HTTP request to `nc` didn't seem to work. With curl, you can use the `-d` flag to `POST` a JSON request to the server.

For example, in the following:

    curl -d '[1,"getProducts",1,0,{}]' -H "Content-Type: application/vnnd.apache.thrift.json; charset=utf-8" http://codecheker.url/v6.24/Products

Thrift requests look weird a bit in JSON. Above is the example for a normal request without argument. One with arguments looks like this:

    [1,"getPermissionsForUser",1,0,{"1":{"str":"SYSTEM"},"2":{"str":""},"3":{"rec":{"1":{"tf":1}}}}]

The easiest way is to figure out how a request looks is to just open the "Inspect element" view in a browser against a local dummy instance. 

Curl will, without a fuss, reply just the bare JSON that the server sends:

    [1,"getProducts",3,0,{"1":{"str":"Error code 401: Unauthorized!"},"2":{"i32":6}}]

In this case, this is an exception reply. A valid reply looks like this:

   ╰─ curl -d '[1,"getNotificationBannerText",1,0,{}]' ...
    [1,"getNotificationBannerText",2,0,{"0":{"str":"8J+nnSBXaGlzcGVyaXR5IFJlc3VsdCBzZXJ2ZXI="}}]

If it ends with 2,0,[object] it's a valid reply, 3,0,[object] is a `throw`. But the encoding of parameters is beyond me...


```diff
-            client_host, client_port = self.client_address
+            client_host, client_port = self.client_address[:2]
```

This line seems fishy to me. `--not-host-only` sets the bind address to `0.0.0.0` and this thing should be a pair. Testing this statement in the interpreter make it behave as if the `[:2]` was not added.

What does `netstat` say? Is the server *really* listening on IPv6?

**Comment by irishrover** [comment] 2020-05-05 09:32
Thanks.

I ran curl and got:

```
root@vla2:/# curl -d '[1,"getProducts",1,0,{}]' -H "Content-Type: application/vnnd.apache.thrift.json; charset=utf-8" http://[::1]:8080/v6.24/Products
[1,"getProducts",2,0,{"0":{"lst":["rec",1,{"1":{"i64":1},"2":{"str":"Default"},"3":{"str":"RGVmYXVsdA=="},"4":{"str":"RGVmYXVsdCBwcm9kdWN0IGNyZWF0ZWQgYXQgc2VydmVyIHN0YXJ0Lg=="},"5":{"tf":1},"6":{"tf":1},"7":{"tf":1},"8":{"i32":0},"9":{"i64":0},"10":{"str":""},"12":{"lst":["str",0]},"13":{"lst":["str",0]}}]}}]

```
So it looks like getProducts works.

**Comment by irishrover** [comment] 2020-05-05 12:03
Well, I've got

```
Uncaught TypeError: Thrift.copyList is not a function
    at new codeCheckerDBAccess_v6.ReportFilter (report_server_types.js:2145)
    at new codeCheckerDBAccess_v6.codeCheckerDBAccess_getRunResultCount_args (codeCheckerDBAccess.js:1734)
    at codeCheckerDBAccess_v6.codeCheckerDBAccessClient.send_getRunResultCount (codeCheckerDBAccess.js:7575)
    at codeCheckerDBAccess_v6.codeCheckerDBAccessClient.getRunResultCount (codeCheckerDBAccess.js:7562)
    at Object.notify (ReportCount.js:45)
    at BugFilterView.js:597
    at Array.forEach (<anonymous>)
    at Object.notifyAll (BugFilterView.js:595)
    at Object.initAll (BugFilterView.js:589)
    at Object.postCreate (BugFilterView.js:493)
```
Seems something wrong with my Thrift compiler of it's JS wrapper?

**Comment by whisperity** [comment] 2020-05-05 12:11
Wow... I would try recompiling the image from scratch, ensure that the proper Thrift versions are used... both for Python and for JS. The response from the server itself seems valid as it is.

Did this only come up when switching to IPv6?

**Comment by irishrover** [comment] 2020-05-05 12:16
I have recompiled the Docker image few times - the result is the same. May be "FROM python:3.7 as builder" contains the old Thrift version?

When I run this image locally on my Mac, everything works perfectly. But the same image loaded on Linux server (Ubuntu 16) fails.

**Comment by irishrover** [comment] 2020-05-05 14:14
OMG!
It was a cookie conflict! I just have removed all the cookies and then I began to work properly...

**Comment by whisperity** [comment] 2020-05-05 16:08
🤯 That's weird considering curl replied properly to a local request without a cookie header. Or you mean something was wrong in the browser?

**Comment by irishrover** [comment] 2020-05-05 17:36
> 🤯 That's weird considering curl replied properly to a local request without a cookie header. Or you mean something was wrong in the browser?

Yes, the browser issue - it reused the cookies from the previously installed version of the CodeChecker.

**Comment by Xazax-hun** [comment] 2020-05-06 08:04
Regardless of this issue being solved, adding official ipv6 support upstream might be useful :)

**Comment by irishrover** [comment] 2020-05-06 08:13
> Regardless of this issue being solved, adding official ipv6 support upstream might be useful :)

Yes, sure.
JFYI my ugly IPv6 hack-o-fix works.

**Comment by whisperity** [comment] 2020-05-06 11:11
@Xazax-hun Starting from Python 3.8, simply giving an IPv6 address to the server (`--host ::1`) would make it listen IPv6.

I'm making a patch for 3.6 and 3.7 (@gyorb said we require 3.6), and there's a few more nits here and there to make sure everything works as intended.

**Comment by whisperity** [comment] 2020-05-06 11:51
> Yes, the browser issue - it reused the cookies from the previously installed version of the CodeChecker.

@irishrover I do not think it was the cookies, but rather the JavaScript stuff being cached, as per detailed in #2228.
Anyways, thanks for the report, with the patch being merged I hope we can officially support a proper IPv6 binding. Until then, yeah, setting the `address_family` is the crucial part of the hack.

**Closed** 2020-06-05 13:48 UTC
Labels: config :gear:, server :desktop_computer:
